config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  resources :tasks do
    get :search, on: :collection
  end
  resources :users
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :due_date, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  accepts_nested_attributes_for :labels, allow_destroy: true
  
  #scope、クラスメソッド（モデルクラスに対して働きかけるメソッド）のように呼び出せる
  scope :created_at_sort, -> { order(created_at: :desc) }
  scope :due_date_sort, -> { order(due_date: :desc) }
  scope :priority_sort, -> { order(priority: :desc) }
  scope :title_search, -> (title) { where("title LIKE ?", "%#{ title }%") }
  scope :status_search, -> (status) { where(status: status) }
  scope :title_status_search, -> (title, status) { where("title LIKE ?", "%#{ title }%").where(status: status) }

  # enumを使えば、数字を意味のある文字として扱える。DBには割り当てられた整数が保存される。
  enum status: { 未着手: 0, 着手中: 1, 完了: 2 }
  enum priority: { 低: 0, 中: 1, 高: 2 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only:[:show, :edit, :update, :destroy]

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.due_date_sort.page(params[:page])
    elsif params[:priority_expired]
      @tasks = current_user.tasks.priority_sort.page(params[:page])
    else
      @tasks = current_user.tasks.created_at_sort.page(params[:page])
    end
  end

  def search
    if params[:task].present?
      if params[:task][:title].present? && params[:task][:status].present?
        @tasks = Task.title_status_search(params[:task][:title],params[:task][:status]).page(params[:page])
        render :index
      elsif params[:task][:title].present?
        @tasks = Task.title_search(params[:task][:title]).page(params[:page])
        render :index
      elsif params[:task][:status].present?
        @tasks = Task.status_search(params[:task][:status]).page(params[:page])
        render :index
      elsif params[:task][:label_id].present?
        @tasks = Label.label_search(params[:task][:label_id]).page(params[:page])
        render :index
      end
    end
  end
  # @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to tasks_path, notice: '保存しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: '保存しました'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: '削除しました'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :due_date, :status, :priority, labels_attributes: [:name], label_ids: [])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <h2><%= pluralize(task.errors.count, "error") %> prohibited this task form being saved</h2>
    <ul>
      <% task.errors.each do |task| %>
      <li><%= task.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <p><%= f.label :title %><br/ >
  <%= f.text_field :title %></p>

  <p><%= f.label :content %><br/ >
  <%= f.text_area :content %></p>

  <p><%= f.label :due_date %><br/ >
  <%= f.date_field :due_date %></p>

  <p><%= f.label :status %><br/ >
  <%= f.select :status, Task.statuses.keys %></p>
  
  <p><%= f.label :priority %><br/ >
  <%= f.select :priority, Task.priorities.keys %></p>

  <p><%= f.collection_check_boxes(:label_ids, Label.all, :id, :name) %></p>
  
  <%= f.submit '登録する' %>

<% end %>

<% link_to 'Back', tasks_path %>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= form_with(scope: :task, url: search_tasks_path, method: :get, local: true) do |f|%>
  <%= f.label :title_search %>
  <%= f.text_field :title %>
  <%= f.label :status_search %>
  <%= f.select :status, Task.statuses.keys, include_blank: true %>
  <%= f.label :label_search %>
  <%= f.select(:label_id, Label.pluck(:name, :id), { include_blank: true }) %>
  <%= f.submit 'Search' %>
<% end %>

<table>
  <tr>
    <th>Task</th>
    <th>内容</th>
    <th><%= link_to "終了期限", tasks_path(sort_expired: "true") %></th>
    <th>ステータス<th>
    <th><%= link_to "優先度", tasks_path(sort_priority: "true") %></th>
    <th>ユーザー名</th>
  </tr>
  <% @tasks.each do |task| %>
    <tr class="task_row">
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.due_date %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= task.user.name %></td>
      <td><%= link_to '詳細', task_path(task), class: "btn btn-info" %></td>
      <% if task.user == current_user %>
        <td><%= link_to '編集', edit_task_path(task), class: "btn btn-secondary" %></td>
        <td><%= link_to '削除', task_path(task), method: :delete, data: { confirm: '本当に削除しても良いですか？' }, class: "btn btn-dark" %></td>
      <% end %>
      <td>
        <% task.labels.each do |label| %>
          <%= label.name %>
        <% end %>
      </td>
      </tr>
  <% end %>
</table>
<%= link_to 'Create new Task', new_task_path, class: "btn btn-primary" %>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>New</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1>Show</h1>
<p>Task: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>
<p>ユーザー名：　<%= @task.user.name %></p>
<p>ラベル：　<% @task.labels.each do |label| %><%= label.name %><% end %></p>

<%= link_to 'Back', tasks_path %>