config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  resources :tasks do
    get :search, on: :collection
  end
  resources :users
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum:30 }
  validates :email, presence: true, length: { maximum:255 }, uniqueness: true,
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum:6 }
  before_destroy :should_not_destroy_admin
  has_many :tasks, dependent: :destroy

  private
  def should_not_destroy_admin
  # 管理者権限を持つユーザーが１名かつ@userが管理者権限を持っていたら ->trueのとき、throw(:abort)でrollbackを起こす。
  throw(:abort) if User.where(admin: true).count == 1 && self.admin?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :admin_user
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.select(:id, :name, :email, :created_at, :updated_at, :admin).includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "保存しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: '保存しました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: '削除しました'
  end

  private
  def admin_user
    if !current_user.admin?
      redirect_to tasks_path, notice: '管理者以外はアクセス出来ません'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    else
      render :new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: "保存しました"
    else
      render :new
    end
  end

  def show
    if current_user.id != @user.id
      redirect_to tasks_path, notice: "ユーザが異なりアクセス出来ません"
    else
      render :show
    end

  end

  def edit
    if current_user.id != @user.id
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '保存しました'
    else
      render :edit
    end
  end

  private

  #paramsメソッドで表示するUserのID取得
  def set_user
    @user = User.find(params[:id])
  end

  #strong parameters,送られてきているパラメーターの値の正当性をホワイトリストにてチェック
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model:user, local:true) do |f| %>

  <% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email%>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path(@user.id) %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス：<%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user.id) %>
<%= link_to 'Back', new_session_path %>